[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = ":electric-plug:"

[[pages]]
path = "eda.py"
name = "Exploratory Data Analysis"
icon = ":chart_with_upwards_trend:"

#[[pages]]
#name = "My section"
#icon = "ğŸˆï¸"
#is_section = true

# Pages after an `is_section = true` will be indented
#[[pages]]
#name = "Another page"
#icon = "ğŸ’ª"